# Generated by Django 2.2.19 on 2021-07-26 19:25

import blog.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210726_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[750, 530], upload_to=blog.models.post_image),
        ),
    ]
